name: carla97
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - astor=0.8.1
  - blas=1.0
  - bzip2=1.0.6
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - cairo=1.14.12
  - certifi=2020.12.5
  - cffi=1.14.0
  - cudatoolkit
  - cudnn
  - cupti=9.2.148
  - cytoolz=0.8.2
  - dask-core=2020.12.0
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.2.10
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=2.8.1
  - freetype=2.10.4
  - gast=0.4.0
  - geos=3.8.0
  - glib=2.65.0
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - imageio
  - imgaug
  - intel-openmp
  - jasper=2.0.14
  - joblib=0.11
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib-base=3.1.3
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - mock=2.0.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1j
  - pbr=1.10.0
  - pcre=8.44
  - pillow=8.1.0
  - pixman=0.34.0
  - py-opencv=3.4.2
  - pycparser=2.20
  - pyparsing=2.4.7
  - pyqt=5.6.0
  - python=3.6.10
  - pytorch
  - pytz=2017.2
  - pywavelets=1.1.1
  - pyyaml=3.12
  - qt=5.6.3
  - readline=8.0
  - scikit-learn=0.23.2
  - shapely=1.7.1
  - sip=4.18
  - six=1.15.0
  - sqlite=3.32.3
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.8.2
  - torchvision
  - tornado=4.5.2
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.1.6
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pip==21.1.1
    - action==1.4.4
    - annot==0.0.3
    - atari-py==0.2.6
    - branches==0.1.1
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==8.0.3
    - cloudpickle==1.3.0
    - command==0.1.0
    - configparser==5.1.0
    - csvtomd==0.3.0
    - cvui==2.7
    - cycler==0.10.0
    - dataclasses==0.8
    - docker-pycreds==0.4.0
    - expert==0.0.0.20200723
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.18
    - glfw==1.11.2
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.30.0
    - gym==0.17.2
    - hydra==2.5
    - idna==2.10
    - importlib-metadata==1.7.0
    - kiwisolver==1.2.0
    - kornia==0.3.1
    - location==0.0.7
    - lxml==4.5.2
    - markdown==3.1.1
    - matplotlib==3.3.4
    - moviepy==1.0.3
    - networkx==2.4
    - oauthlib==3.1.0
    - opencv-contrib-python==4.1.2.30
    - opencv-python==4.1.0.25
    - pandas==1.1.5
    - pathtools==0.1.2
    - pip==21.1.1
    - plotly==4.8.2
    - proglog==0.1.9
    - promise==2.3
    - protobuf==3.12.2
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygame==1.9.6
    - pyglet==1.5.0
    - pyopengl==3.1.5
    - python-dateutil==2.8.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.6
    - scikit-image==0.17.2
    - scipy==1.5.1
    - seaborn==0.11.1
    - sentry-sdk==1.5.0
    - setuptools==56.2.0
    - shortuuid==1.0.8
    - smmap==5.0.0
    - subprocess32==3.5.4
    - tb-nightly==2.3.0a20200710
    - termcolor==1.1.0
    - tifffile==2020.7.4
    - torch==1.5.0
    - tqdm==4.47.0
    - typing-extensions==4.0.1
    - urllib3==1.25.9
    - wandb==0.12.7
    - yaspin==2.1.0
    - zipp==3.1.0